### ISSUE TITLE
Babel Loader Problem: Building an App for graphical perception experiments

### ISSUE THREAD

**Issue by G3Di** [vriajs/vria#3]
Dear VRIA Team,

when I want to build a simple page used with the Magic Leap I get the following error:
![error](https://user-images.githubusercontent.com/55146230/124150542-f3c7c200-da91-11eb-8073-a70e7f20acf2.PNG)

Is this a problem of vria-modern.js?

Kind regards

**Comment by PButcher** [comment]
Hi @G3Di, I haven't seen this error before. Is this appearing on the magic leap itself, or elsewhere?

Also, I noticed you closed the issue, does that mean you found a fix? If so, can you post a repro?

**Comment by G3Di** [comment]
Hello! Thanks for your response. To be honest, it was a bit mysterious on the main development machine. On this was machine we were unable to work but on all other machines VRIA in the actual version is working. Which means we are building the experiment app for the paper content. I will try to investigate further what is going on and if I found the solution, I´ll publish it here.

**Comment by PButcher** [comment]
I appreciate that. We're building modern JS and the error message there suggests that the browser instance doesn't support the null coalescing `??` operator syntax and needs some extra Babel loaders, which is odd because VRIA builds have worked for me in every browser I've tested.

If you do find a solution with your setup, please let me know!
